# GET http://localhost:3000/user

###

GET http://localhost:3000/dogs

###

GET http://localhost:3000/dogs/1?bday=2019-03-40

###

POST http://localhost:3000/dogs
Content-Type: application/json
Authorization: user

{

  "name": "Buddy",
  "age": 1,
  "breed": "Labrador",
  "isGoodBoy": true
}

###

PATCH http://localhost:3000/dogs/1
Content-Type: application/json

{
    "age": 5
}

###

DELETE http://localhost:3000/dogs/2
Authorization: user

###

# GET http://localhost:3000/dogs/redirect?lang=123