GET http://localhost:3000/dogs

###

GET http://localhost:3000/dogs/2

###

POST http://localhost:3000/dogs
Content-Type: application/json

{

  "name": "Tofu",
  "age": 1,
  "breed": "Labrador",
  "isGoodBoy": true
}

###

PATCH http://localhost:3000/dogs/1
Content-Type: application/json

{
    "age": 4
}

###

DELETE http://localhost:3000/dogs/1

###

# GET http://localhost:3000/dogs/redirect?lang=123